# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.1.dev22+g82faabd.d20230822'
__version_tuple__ = version_tuple = (0, 1, 1, 'dev22', 'g82faabd.d20230822')
