name: deploy

on: push

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    environment: release
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build XRFeitoria
        run: |
          pip install wheel
          pip wheel --no-deps --wheel-dir dist .

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
